#!/bin/bash
#lore.sh

echo -e "\n\n\n\n"
read -t 2 -p "=======CHAPITRE 1========"
echo -e "\n\n"
read -t 3 -p "UN SAUVETAGE INNATENDU"
echo -e "\n\n\n"
read -t 3 -p "Après que Link et ses amis aies rassemblés leur force dans la taverne, ceux-ci ont décidés de faire route vers la montagne argentée."
echo -e "\n"
read -t 9 -p "Emblême du département d'Hoenn, ses runes légendaires vertes et scintiyantes sont visibles par delà les nombreuses contrées que recense Runetterra."
echo -e "\n"
read -t 9 -p "Ils marchèrent jour et nuit, leur peau illuminée de la lumière émanant de ce pic qui se rapprochait."
echo -e "\n"
read -t 9 -p "Leurs provisions commençaient à se dissoudre à vue d'oeil, et le pic était encore loin."
echo -e "\n"
read -t 9 -p "Soudain, Hylia sentie une puissance maléfique, émanant d'un rocher encore impercaptible par ses compagnons."
echo -e "\n"
read -t 9 -p "Remuant ciel et terre pour convaincre ses amis, Hylia avait un devoir de d'honneteté, qu'elle ne s'empecha pas d'exprimer."
echo -e "\n"
read -t 1 -p "- Hylia : "
echo -e "\n"
read -t 2 -p "          Votre princesse est retenue là-bas "$"."
echo -e "\n\n"
